add Better-connect-bar snippets
spicetify/marketplace pull request #824
Opened 2024-08-17 09:46 UTC by ZGQ-inc

2025-01-21 06:05 UTC, kyrie25 reviewed
Is the snippet still working/relevant

2025-01-21 06:23 UTC, ZGQ-inc commented
> Is the snippet still working/relevant

It still works on my Spotify version 1.53.440.
By the way, I don't know since which version they changed the `border-radius` from 4px to 8px, whatever.

2025-01-21 07:27 UTC, kyrie25 commented
> It still works on my Spotify version 1.53.440. By the way, I don't know since which version they changed the `border-radius` from 4px to 8px, whatever.

The current latest Spotify version is `1.2.55`, can you check and see if it still works there?

2025-01-21 07:29 UTC, kyrie25 requested changes
Resolve syntax issue

2025-01-21 07:49 UTC, ZGQ-inc commented
> The current latest Spotify version is `1.2.55`, can you check and see if it still works there?

Tested on 1.2.55.235, it works, and they changed `border-radius` back to 4px.

2025-01-21 08:02 UTC, kyrie25 commented
> Tested on 1.2.55.235, it works, and they changed `border-radius` back to 4px.

Nice! I'll look into it after you've resolved the issues, cheers!

2025-02-15 15:00 UTC, ZGQ-inc commented on resources/snippets.json
>    }
sorry for making a dumb mistake, didn't even find that

2025-06-07 23:03 UTC, closed without merging