fix(snippet): Rounded Buttons
spicetify/marketplace pull request #854
Opened 2024-10-19 14:01 UTC by mohvn

Updating the search bar design by rounding its corners to match the style of the other buttons in the interface

Before:
![before](https://github.com/user-attachments/assets/0b37e941-0b6f-481d-86ef-fecba325d123)

After:
![after](https://github.com/user-attachments/assets/c7a24010-80df-4a49-83fe-f3f9961b706f)

2024-10-20 12:46 UTC, Climax12 commented
it's already has rounded corners isn't it?
![image](https://github.com/user-attachments/assets/8a731689-0dbc-41f4-86e6-130013ad7f7a)

2024-10-21 02:46 UTC, mohvn commented
> it's already has rounded corners isn't it? ![image](https://private-user-images.githubusercontent.com/169449725/378188309-8a731689-0dbc-41f4-86e6-130013ad7f7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Nzg5MzEsIm5iZiI6MTcyOTQ3ODYzMSwicGF0aCI6Ii8xNjk0NDk3MjUvMzc4MTg4MzA5LThhNzMxNjg5LTBkYmMtNDFmNC04NmU2LTEzMDAxM2FkN2Y3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwMjQzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2RjNzY3NTQ4N2I5NTAzMzBhYWQwN2EyNDM2NDllMTcyYTc5MzM0ZjcyZjQ1YmZmYmQxMmZlZTNkZGVhYWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._VAHxh7uKRaKkzNDY1soS6kRQuTAWY4-vX5Hr0gIyAA) ![image](https://private-user-images.githubusercontent.com/169449725/378189543-db8df9ec-f3c8-4a87-a290-fcf5d5b34118.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Nzg5MzEsIm5iZiI6MTcyOTQ3ODYzMSwicGF0aCI6Ii8xNjk0NDk3MjUvMzc4MTg5NTQzLWRiOGRmOWVjLWYzYzgtNGE4Ny1hMjkwLWZjZjVkNWIzNDExOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwMjQzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzNiYzRjOGNhMGFhMWExMzY1MjUwODUxNzJhYzQxZmY2ODc2ZGMzNmZkNjJmNGU3ZjU0M2I5OGVkZjFlYTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eGmeRi94-f-8KwcEn_zlyUn9KQovYwplkVuOvWSp82w)
> 
> edit: i was using older version, I think spotify has been changed :) edit2: for me it's still working
> 
> > spotify version: 1.2.47.364.gf06e5cee
> > spicetify version: 2.38.4

![image](https://github.com/user-attachments/assets/6119e938-7fa8-4409-bf27-e74284ce23ea)

Not working in my Spotify

Spotify for Windows (64 bit)
1.2.48.405.gf2c48e6f

2024-10-21 10:48 UTC, Climax12 commented
> > it's already has rounded corners isn't it? ![image](https://private-user-images.githubusercontent.com/169449725/378188309-8a731689-0dbc-41f4-86e6-130013ad7f7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Nzg5MzEsIm5iZiI6MTcyOTQ3ODYzMSwicGF0aCI6Ii8xNjk0NDk3MjUvMzc4MTg4MzA5LThhNzMxNjg5LTBkYmMtNDFmNC04NmU2LTEzMDAxM2FkN2Y3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwMjQzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2RjNzY3NTQ4N2I5NTAzMzBhYWQwN2EyNDM2NDllMTcyYTc5MzM0ZjcyZjQ1YmZmYmQxMmZlZTNkZGVhYWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._VAHxh7uKRaKkzNDY1soS6kRQuTAWY4-vX5Hr0gIyAA) ![image](https://private-user-images.githubusercontent.com/169449725/378189543-db8df9ec-f3c8-4a87-a290-fcf5d5b34118.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Nzg5MzEsIm5iZiI6MTcyOTQ3ODYzMSwicGF0aCI6Ii8xNjk0NDk3MjUvMzc4MTg5NTQzLWRiOGRmOWVjLWYzYzgtNGE4Ny1hMjkwLWZjZjVkNWIzNDExOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwMjQzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzNiYzRjOGNhMGFhMWExMzY1MjUwODUxNzJhYzQxZmY2ODc2ZGMzNmZkNjJmNGU3ZjU0M2I5OGVkZjFlYTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eGmeRi94-f-8KwcEn_zlyUn9KQovYwplkVuOvWSp82w)
> > edit: i was using older version, I think spotify has been changed :) edit2: for me it's still working
> > > spotify version: 1.2.47.364.gf06e5cee
> > > spicetify version: 2.38.4
> 
> ![image](https://private-user-images.githubusercontent.com/57570197/378255416-6119e938-7fa8-4409-bf27-e74284ce23ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDc2MjYsIm5iZiI6MTcyOTUwNzMyNiwicGF0aCI6Ii81NzU3MDE5Ny8zNzgyNTU0MTYtNjExOWU5MzgtN2ZhOC00NDA5LWJmMjctZTc0Mjg0Y2UyM2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDEwNDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNWExZTgyZmU0NmViZGVlOWUyN2RiMmE5ZjIwY2E2YzAyZTcxN2E3YzcxMjQyNmNhYWQ4ZGZmNGNkY2I0NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YXmB7gFzHhzywY_oMSP0jZFbDRVqIQGTpGXI9w5yjko)
> 
> Not working in my Spotify
> 
> Spotify for Windows (64 bit) 1.2.48.405.gf2c48e6f
> 
> Spicetify v2.38.4

I just logged in to windows 

ya, Mine also not showing :) 

![image](https://github.com/user-attachments/assets/9069549a-af53-4fba-b11a-150a1008b694)

> Spotify for Windows (64 bit) 1.2.48.405.gf2c48e6f
> Spicetify v2.38.4

2024-10-26 17:45 UTC, Climax12 commented
`.x-filterBox-expandButton, .main-avatar-avatar, .main-topBar-buddyFeed, .main-topBar-button, .Button-sc-1dqy6lx-0, .main-coverSlotCollapsed-expandButton, .NqzueDshzvgXEygqOGPG {border-radius: 15% !important;} .XNFZdOLgMlx491fEWdYJ, .ChipClear__ChipClearComponent-sc-zv5btm-0, .Button-sc-1dqy6lx-0, .Button-sc-y0gtbx-0, .main-nowPlayingView-aboutArtistV2FollowButton, .main-playPauseButton-button, .ButtonInner-sc-14ud5tc-0, .search-searchCategory-carouselButton, .ChipInnerComponent-sm, .ChipInnerComponent-sm-selected, .switch, .arrow-btn, .pSxFsY9Fgcj5f8Gf05mh, .qyKJPLjz8o4jnbk92JOn, .reset, .rdp-button, .btn, .TabItem__StyledTabItem-sc-2ani5y-0  {border-radius: 6px !important;} .view-homeShortcutsGrid-playButton, .ButtonInner-medium-iconOnly,  .button-module__button___hf2qg_marketplace {border-radius: 10px !important;} .ButtonInner-large-iconOnly {border-radius: 12px !important;} .main-globalNav-searchInputContainer, .SFAoASy0S_LZJmYZ3Fh9, .x-searchInput-searchInputInput,  .toggle-module__toggle-indicator-wrapper___6Lcp0_marketplace, .x-toggle-indicatorWrapper, .main-topBar-searchBar {border-collapse: separate; border-radius: 6px !important;}`

add this, it will fix it
since you have opens this pr, so i don't need to add another pr to fix search bar in search page

2024-11-27 11:18 UTC, mohvn commented
> `.x-filterBox-expandButton, .main-avatar-avatar, .main-topBar-buddyFeed, .main-topBar-button, .Button-sc-1dqy6lx-0, .main-coverSlotCollapsed-expandButton, .NqzueDshzvgXEygqOGPG, .main-embedWidgetGenerator-themeRadio, .Psc33HXPyazZYAAr1tgz {border-radius: 15% !important;} .XNFZdOLgMlx491fEWdYJ, .ChipClear__ChipClearComponent-sc-zv5btm-0, .Button-sc-1dqy6lx-0, .Button-sc-y0gtbx-0, .main-nowPlayingView-aboutArtistV2FollowButton, .main-playPauseButton-button, .ButtonInner-sc-14ud5tc-0, .search-searchCategory-carouselButton, .ChipInnerComponent-sm, .ChipInnerComponent-sm-selected, .switch, .arrow-btn, .pSxFsY9Fgcj5f8Gf05mh, .qyKJPLjz8o4jnbk92JOn, .reset, .rdp-button, .btn, .TabItem__StyledTabItem-sc-2ani5y-0, .main-playlistEditDetailsModal-closeBtn, .main-embedWidgetGenerator-closeBtn, .Chip__ChipComponent-sc-ry3uox-0 {border-radius: 6px !important;} .view-homeShortcutsGrid-playButton, .ButtonInner-medium-iconOnly, .button-module__button___hf2qg_marketplace {border-radius: 10px !important;} .ButtonInner-large-iconOnly {border-radius: 12px !important;} .main-globalNav-searchInputContainer, .SFAoASy0S_LZJmYZ3Fh9, .x-searchInput-searchInputInput, .toggle-module__toggle-indicator-wrapper___6Lcp0_marketplace, .x-toggle-indicatorWrapper, .main-topBar-searchBar {border-collapse: separate; border-radius: 6px !important;}`
> 
> add this, since you have opened this pr, I not going to make another pr to fix search bar in search page and other minor fixes. 🙂

Thanks, added this fixes to the pr, but still waiting for so long for the review

2024-11-27 12:50 UTC, theRealPadster requested changes

2024-11-27 12:50 UTC, theRealPadster commented on resources/snippets.json
> +]
Needs newline at end of file

2024-11-27 12:53 UTC, mohvn commented on resources/snippets.json
> +]
got it

2024-11-27 14:24 UTC, theRealPadster approved these changes

2024-11-27 14:25 UTC, merged