feat(snippets): "Shonky"
spicetify/marketplace pull request #872
Opened 2024-12-15 17:11 UTC by regedit-sys

2025-01-28 23:40 UTC, regedit-sys commented
I _think_ I fixed it, lmk if I need to make any other changes.

2025-01-29 02:19 UTC, kyrie25 requested changes
Resolve syntax & linting issues, make sure your changes work after.

2025-02-15 14:36 UTC, Climax12 commented on resources/snippets.json
>      "title": "Circular shadow fix for album art",
fix
```suggestion
  {
    "title": "Circular shadow fix for album art",
```

2025-06-07 23:05 UTC, rxri commented
Inactivity. Closing

2025-06-07 23:05 UTC, closed without merging