feat(snippets): add two new snippets
spicetify/marketplace pull request #873
Opened 2024-12-21 17:04 UTC by MigProPlayer

Adds two new snippets and their assets:

- Remove Duplicated Fullscreen Button - Removes the original fullscreen button when the Beautiful Lyrics extension is installed.
- Fix Listen Together Button - Changes the button from the Listen Together extension to match the rest of the UI and theme.

2025-01-20 06:30 UTC, kyrie25 requested changes
Resolve conflicts

2025-01-25 19:35 UTC, MigProPlayer commented
Conflicts solved 👍

2025-01-26 01:47 UTC, kyrie25 requested changes
Fix syntax/lint issue

2025-02-07 13:48 UTC, Climax12 commented on resources/snippets.json
bro you fogot to add "{" at line 470 🫡

2025-02-08 13:33 UTC, MigProPlayer commented on resources/snippets.json
sorry, it's fixed now!

2025-02-08 13:34 UTC, MigProPlayer commented
Sorry it took so long, but everything should now be fixed and ready to merge!

2025-02-09 12:42 UTC, kyrie25 approved these changes

2025-02-09 12:43 UTC, kyrie25 reviewed
Rebase & resolve conflict with main branch

2025-02-15 14:19 UTC, rxri approved these changes

2025-02-15 14:19 UTC, merged